### ISSUE TITLE
可以用@RestController

### ISSUE THREAD

**Issue by Rayooo** [dreamhuan/workStudyManagement#1]
@RestController 相当于 为Controller的每个方法打上@ResponseBody

**Comment by dreamhuan** [comment]
好的好的，本来考虑每个controller的第一个get方法返回jsp，后来都挪到url的controller里了也忘记换了。。。感觉view层用了jsp简直自虐。。。

**Comment by Rayooo** [comment]
前端我用Vue很舒服

**Comment by dreamhuan** [comment]
现在换已经来不及了…  有空我也去看看vue
